import { Context } from "probot";
import { analyzeContent } from "../services/analysisClient";
import { CommentBuilder } from "../services/commentBuilder";
import { handleSurge } from "./surgeHandler";

const comments = new CommentBuilder();
const ANALYSIS_ENGINE_URL = process.env.ANALYSIS_ENGINE_URL || "http://localhost:8000";

export async function handlePullRequest(
  context: Context<"pull_request.opened" | "pull_request.synchronize">
) {
  const pr = context.payload.pull_request;
  const { owner, repo } = context.repo();
  const octokit = context.octokit as any;

  if (context.payload.action === "opened") {
    const isSurge = await handleSurge(context as any);
    if (isSurge) return;
  }

  context.log.info("Processing PR #" + pr.number + ": " + pr.title);

  try {
    if (!pr.user) return;

    const diffRes = await octokit.request("GET /repos/{owner}/{repo}/pulls/{pull_number}", {
      owner, repo, pull_number: pr.number,
      headers: { accept: "application/vnd.github.diff" },
    });
    const diff = typeof diffRes.data === "string" ? diffRes.data : "";
    const content = pr.title + "\n\n" + (pr.body || "") + "\n\n--- DIFF ---\n" + diff;

    const result = await analyzeContent({
      content,
      content_type: "diff",
      repo_id: owner + "/" + repo,
      contributor_login: pr.user.login,
      contributor_id: pr.user.id,
    });

    context.log.info("PR #" + pr.number + " score: " + result.overall_score + " -> " + result.label);

    if (result.label !== "human") {
      await octokit.request("POST /repos/{owner}/{repo}/issues/{issue_number}/labels", {
        owner, repo, issue_number: pr.number, labels: [result.label]
      });
    }

    if (result.contributor_trust_score < 30) {
      await octokit.request("POST /repos/{owner}/{repo}/issues/{issue_number}/labels", {
        owner, repo, issue_number: pr.number, labels: ["first-time-contributor"]
      });
    }

    const report = comments.buildReport(result);
    await octokit.request("POST /repos/{owner}/{repo}/issues/{issue_number}/comments", {
      owner, repo, issue_number: pr.number, body: report
    });

    if (result.overall_score > 0.5) {
      context.log.info(`Generating smart review for PR #${pr.number}...`);
      try {
        const reviewRes = await fetch(ANALYSIS_ENGINE_URL + "/review/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            diff: diff || "",
            pr_title: pr.title,
            pr_body: pr.body || "",
            pr_labels: pr.labels.map((label: any) => label.name),
            repo_id: owner + "/" + repo,
            slop_score: result.overall_score
          })
        });
        context.log.info(`Smart review API response status: ${reviewRes.status}`);

        let reviewData;
        try {
            reviewData = await reviewRes.json() as any;
        } catch (e: any) {
            throw new Error(`Failed to parse review JSON: ${e.message}`);
        }
        
        const reviewText = reviewData.review || "";
        const verdict = reviewData.verdict || "comment";
        const inlineComments = reviewData.inline_comments || [];
        
        if (reviewText.trim()) {
          // Map LLM verdict to GitHub PR review events: APPROVE, REQUEST_CHANGES, COMMENT
          let event: "APPROVE" | "REQUEST_CHANGES" | "COMMENT" = "COMMENT";
          if (verdict === "approve" && result.overall_score < 0.4) {
            event = "APPROVE";
          } else if (verdict === "request_changes" || result.overall_score >= 0.6) {
            event = "REQUEST_CHANGES";
          }

          // Map inline comments to GitHub review API schema
          const gitHubComments = inlineComments.map((c: any) => ({
            path: c.path,
            line: Number(c.line),
            body: c.comment
          })).filter((c: any) => c.path && c.line && c.body);

          await octokit.request("POST /repos/{owner}/{repo}/pulls/{pull_number}/reviews", {
            owner,
            repo,
            pull_number: pr.number,
            body: `## 🤖 Guardian AI Co-Maintainer Review\n\n${reviewText}\n\n---\n*This review was auto-generated by the AI Co-Maintainer.*`,
            event,
            comments: gitHubComments.length > 0 ? gitHubComments : undefined
          });
          context.log.info(`Structured PR review submitted with event: ${event}`);

          // Auto-merge if approved and is safe (low slop score)
          if (event === "APPROVE" && result.overall_score < 0.3) {
            context.log.info(`PR #${pr.number} is fully approved by AI Co-Maintainer with safe slop score. Triggering automated merge...`);
            
            // Add GSSoC and enhancement labels
            await octokit.request("POST /repos/{owner}/{repo}/issues/{issue_number}/labels", {
              owner,
              repo,
              issue_number: pr.number,
              labels: ["GSSoC", "enhancement"]
            });

            // Perform merge
            await octokit.request("PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge", {
              owner,
              repo,
              pull_number: pr.number,
              merge_method: "squash",
              commit_title: `chore: auto-merge PR #${pr.number} by AI Co-Maintainer`,
              commit_message: `Merged automatically by Slop Guardian AI Co-Maintainer after passing all slop verifications and code reviews.`
            });
            context.log.info(`PR #${pr.number} successfully auto-merged.`);
          }
        } else {
          context.log.warn("Smart review was empty for PR #" + pr.number);
        }
      } catch (reviewErr: any) {
        context.log.error("Failed to generate smart review: " + reviewErr.message);
      }
    }

    if (result.overall_score > 0.60) {
      context.log.info(`Generating comprehension challenge for PR #${pr.number} (score: ${result.overall_score})...`);
      try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 30000);

        const challengeRes = await fetch(ANALYSIS_ENGINE_URL + "/challenge/generate", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          signal: controller.signal,
          body: JSON.stringify({
            diff: diff.substring(0, 2000),
            pr_title: pr.title,
            repo_id: owner + "/" + repo
          })
        });
        clearTimeout(timeoutId);
        context.log.info(`Challenge API response status: ${challengeRes.status}`);

        let challenge;
        try {
            challenge = await challengeRes.json() as any;
        } catch (e: any) {
            throw new Error(`Failed to parse challenge JSON: ${e.message}`);
        }
        
        const questions = challenge.questions || [];
        if (questions.length === 0) {
            throw new Error("No questions returned from challenge endpoint");
        }

        const challengeComment = [
          "## Comprehension Challenge",
          "",
          "Guardian flagged this PR as potentially AI-generated (" + Math.round(result.overall_score * 100) + "% probability).",
          "Please answer these questions to verify authorship:",
          "",
          ...questions.map((q: string, i: number) => (i + 1) + ". " + q),
          "",
          "Reply with /guardian answer [your answers] within 48 hours.",
          "",
          "_Challenge ID: " + (challenge.challenge_id || "unknown") + "_"
        ].join("\n");
        await octokit.request("POST /repos/{owner}/{repo}/issues/{issue_number}/comments", {
          owner, repo, issue_number: pr.number, body: challengeComment
        });
        context.log.info("Comprehension challenge posted on PR #" + pr.number);
      } catch (challengeErr: any) {
        context.log.error("Failed to post challenge: " + challengeErr.message);
        const fallbackComment = [
          "## 🧠 Authorship Verification Required",
          `This PR was flagged as potentially AI-generated (${Math.round(result.overall_score * 100)}% probability).`,
          "Please describe in a comment:",
          "1. What problem does this PR solve?",
          "2. Walk us through your implementation approach",
          "3. What did you test and how?"
        ].join("\n");
        await octokit.request("POST /repos/{owner}/{repo}/issues/{issue_number}/comments", {
          owner, repo, issue_number: pr.number, body: fallbackComment
        });
        context.log.info("Fallback comprehension challenge posted on PR #" + pr.number);
      }
    }

  } catch (err: any) {
    context.log.error("Error processing PR #" + pr.number + ": " + err.message);
  }
}
 